# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: mac-agent
    steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerHub'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerHub'
    repository: 'docker-test'
    command: 'build'
    Dockerfile: '/aspnet-mssql/app/aspnetapp/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerHub'
    repository: 'docker-test'
    command: 'push'
