# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

parameters:
- name: tag
  type: string
  default: 'samucasouza'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: mac-agent
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'test-docker'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/aspnet-mssql/app/aspnetapp/Dockerfile'
          tags: '${{ parameters.tag }}'