# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- prod

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Deploy
    displayName: DeployVMProd1
    pool: VMProd1
    steps:
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: 'dockerHub'
          dockerComposeFile: '$(Build.SourcesDirectory)/aspnet-mssql/compose.yaml'
          projectName: 'samucasouza/test-docker'
          action: 'Run a Docker Compose command'
          dockerComposeCommand: 'up -d --force-recreate'
          dockerComposePath: '/home/azureuser/.docker/cli-plugins/docker-compose'

  - job: Deploy
      displayName: DeployVMProd2
      dependsOn: Deploy
      pool: VMProd2
      steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'dockerHub'
            dockerComposeFile: '$(Build.SourcesDirectory)/aspnet-mssql/compose.yaml'
            projectName: 'samucasouza/test-docker'
            action: 'Run a Docker Compose command'
            dockerComposeCommand: 'up -d --force-recreate'
            dockerComposePath: '/home/azureuser/.docker/cli-plugins/docker-compose'
