# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Dev1
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'samucasouza/test-docker'
          command: 'login'
          
      - task: Docker@2
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'samucasouza/test-docker'
          command: 'build'
          Dockerfile: '$(Build.SourcesDirectory)/aspnet-mssql/app/aspnetapp/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest

      - task: Docker@2
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'samucasouza/test-docker'
          command: 'push'
          tags: |
            $(Build.BuildId)
            latest